CXX ?= g++
CXXFLAGS ?= -O2 -std=c++17 -Wall -Wextra
all: m3FreeSurfaceIntegrationUnit
m3FreeSurfaceIntegrationUnit: m3FreeSurfaceIntegrationUnit.cpp movingPistonConversion.h movingPistonIndicator.h
	$(CXX) $(CXXFLAGS) m3FreeSurfaceIntegrationUnit.cpp -o $@
clean:
	rm -f m3FreeSurfaceIntegrationUnit
