EXAMPLE = ex240_h65_dns
OLB_ROOT := /home/dell/openlb
include $(OLB_ROOT)/default.mk

.PHONY: build
build:
	$(MAKE) ex240_h65_dns EXAMPLE=ex240_h65_dns CPP_FILES=ex240_h65_dns.cpp OBJ_FILES=ex240_h65_dns.o

