EXAMPLE = sim_ec1xt240_directional_dns
OLB_ROOT := /home/dell/openlb
include $(OLB_ROOT)/default.mk

.PHONY: build
build:
	$(MAKE) sim_ec1xt240_directional_dns EXAMPLE=sim_ec1xt240_directional_dns CPP_FILES=sim_ec1xt240_directional_dns.cpp OBJ_FILES=sim_ec1xt240_directional_dns.o

