EXAMPLE = sim_ec1xt240_fixed_gap_dns
OLB_ROOT := /home/dell/openlb
include $(OLB_ROOT)/default.mk

.PHONY: build
build:
	$(MAKE) sim_ec1xt240_fixed_gap_dns EXAMPLE=sim_ec1xt240_fixed_gap_dns CPP_FILES=sim_ec1xt240_fixed_gap_dns.cpp OBJ_FILES=sim_ec1xt240_fixed_gap_dns.o

