# Makefile for the SIM-EC1XT240 abstract straight-groove DNS case.
#
# Builds against the system OpenLB installation at OLB_ROOT.
EXAMPLE = grooveDns
OLB_ROOT := /home/dell/openlb
include $(OLB_ROOT)/default.mk
