#include <olb.h>
#include <algorithm>
#include <array>
#include <cmath>
#include <deque>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <limits>
#include <string>
#include <typeinfo>
#include <vector>
using namespace olb;
using T=double;
using D=descriptors::D3Q19<descriptors::BOUZIDI_DISTANCE,descriptors::BOUZIDI_VELOCITY>;
constexpr T dx=5e-9,dt=1e-11,Lx=240e-9,Ly=240e-9,dg=100e-9,rhoP=1000.,nu=1e-6;
constexpr int overlap=3,trajectorySteps=10000,diagSteps=650,historySteps=20;

class PeriodicXOutside final:public IndicatorF3D<T>{public:PeriodicXOutside(){this->_myMin={-1e9,-1e9,-1e9};this->_myMax={1e9,1e9,1e9};this->getName()="PeriodicXOutside";}bool operator()(bool o[1],const T r[3])override{T e=dx*1e-6;o[0]=r[1]<dx/2-e||r[1]>Ly-dx/2+e||r[2]<-dx/2-e||r[2]>192.5e-9+e;return true;}};
T smooth5(T s){s=std::clamp(s,T(0),T(1));return 10*s*s*s-15*s*s*s*s+6*s*s*s*s*s;}
T dsmooth5(T s){s=std::clamp(s,T(0),T(1));return 30*s*s*(1-s)*(1-s);}
T hAt(int n,bool move){return move?75e-9-10e-9*smooth5(T(n)/trajectorySteps):75e-9;}
T wallSpeed(int n,bool move){return move?-10e-9/(trajectorySteps*dt)*dsmooth5((T(n)-.5)/trajectorySteps):0;}
bool punch(T x,T z,T h){return z>=((x<60e-9||x>=180e-9)?h:h+dg);}
int matAt(const Vector<T,3>&r){if(r[2]<0)return 2;if(punch(r[0],r[2],75e-9))return 3;if(r[1]<dx)return 4;if(r[1]>Ly-dx)return 5;return 1;}

struct CellSnap{int step=0,ix=0,iy=0,iz=0,mat=0;T x=0,y=0,z=0,rho=0,u[3]{},speed=0,mach=0;std::array<T,D::q> f{},q{},bv{};bool lp=false,bouz=false,dual=false,finite=true;};
struct Frame{int step=0;std::vector<CellSnap> cells;};
struct Event{bool set=false;int step=-1,index=-1;std::string kind,dynamics;CellSnap cell;};

template<class B,class G>CellSnap snap(B&b,G&g,LatticeR<3>p,int step){CellSnap s;s.step=step;s.ix=p[0];s.iy=p[1];s.iz=p[2];s.mat=g.getMaterial(p);auto r=g.getPhysR(p);s.x=r[0];s.y=r[1];s.z=r[2];auto c=b.get(p);c.computeU(s.u);s.rho=c.computeRho();s.speed=std::sqrt(s.u[0]*s.u[0]+s.u[1]*s.u[1]+s.u[2]*s.u[2]);s.mach=s.speed/std::sqrt(T(1)/3);std::string dyn=typeid(*b.getDynamics(p[0],p[1],p[2])).name();s.lp=dyn.find("FixedPressureMomentum")!=std::string::npos;for(int i=0;i<D::q;++i){s.f[i]=c[i];s.q[i]=c.template getFieldComponent<descriptors::BOUZIDI_DISTANCE>(i);s.bv[i]=c.template getFieldComponent<descriptors::BOUZIDI_VELOCITY>(i);if(s.q[i]>=0)s.bouz=true;}s.dual=s.lp&&s.bouz;s.finite=std::isfinite(s.rho)&&std::isfinite(s.speed);for(T v:s.f)s.finite&=std::isfinite(v);return s;}

template<class L,class G>std::array<int,3> updateLinks(L&lat,G&geo,T h,T uw){int active=0,invalid=0,dual=0;for(int c=0;c<lat.getLoadBalancer().size();++c){auto&b=lat.getBlock(c);auto&g=geo.getBlockGeometry(c);b.forCoreSpatialLocations([&](LatticeR<3>p){auto cell=b.get(p);for(int q=0;q<D::q;++q){cell.template setFieldComponent<descriptors::BOUZIDI_DISTANCE>(q,-1);cell.template setFieldComponent<descriptors::BOUZIDI_VELOCITY>(q,0);}int m=g.getMaterial(p);if(m!=1&&m!=4&&m!=5)return;auto r=g.getPhysR(p);bool any=false;for(int q=1;q<D::q;++q){auto cv=descriptors::c<D>(q);int sm=g.getMaterial(p+cv);if(sm!=2&&sm!=3)continue;T qq=.5,vc=0;if(sm==3){T lo=0,hi=1;for(int k=0;k<50;++k){T a=(lo+hi)/2;if(punch(r[0]+a*dx*cv[0],r[2]+a*dx*cv[2],h))hi=a;else lo=a;}qq=(lo+hi)/2;vc=cv[2]*uw*dt/dx;}if(qq<0||qq>1)invalid++;else{cell.template setFieldComponent<descriptors::BOUZIDI_DISTANCE>(q,qq);cell.template setFieldComponent<descriptors::BOUZIDI_VELOCITY>(q,vc);active++;any=true;}}if(any&&(m==4||m==5))dual++;});}lat.communicate();return{active,invalid,dual};}

void header(std::ofstream&o){o<<"step,ix,iy,iz,x_nm,y_nm,z_nm,material,rho,ux_lattice,uy_lattice,uz_lattice,speed_lattice,Mach,is_LocalPressure,is_Bouzidi,is_dual,finite";for(int i=0;i<D::q;++i)o<<",f"<<i;for(int i=0;i<D::q;++i)o<<",q"<<i;for(int i=0;i<D::q;++i)o<<",bouzidi_velocity_coeff"<<i;o<<"\n";}
void row(std::ofstream&o,const CellSnap&s){o<<s.step<<","<<s.ix<<","<<s.iy<<","<<s.iz<<","<<s.x*1e9<<","<<s.y*1e9<<","<<s.z*1e9<<","<<s.mat<<","<<s.rho<<","<<s.u[0]<<","<<s.u[1]<<","<<s.u[2]<<","<<s.speed<<","<<s.mach<<","<<s.lp<<","<<s.bouz<<","<<s.dual<<","<<s.finite;for(T v:s.f)o<<","<<v;for(T v:s.q)o<<","<<v;for(T v:s.bv)o<<","<<v;o<<"\n";}

int run(char which){bool move=which!='B',pressure=which!='A';std::string tag(1,which),run="boundary_intersection_diag_"+tag+"_20260907";auto out=std::filesystem::path("output")/run;if(std::filesystem::exists(out)){std::cerr<<"exists "<<out<<"\n";return 2;}std::filesystem::create_directories(out);singleton::directories().setOutputDir((out.string()+"/").c_str());std::ofstream log(out/"run.log");log<<std::setprecision(16)<<std::boolalpha;
 IndicatorCuboid3D<T>dom({Lx-dx,Ly-dx,195e-9},{dx/2,dx/2,-dx/2});CuboidDecomposition<T,3>cub(dom,dx,1);cub.setPeriodicity({true,false,false});HeuristicLoadBalancer<T>load(cub);SuperGeometry<T,3>geo(cub,load,overlap);for(int c=0;c<load.size();++c){auto&g=geo.getBlockGeometry(c);g.forCoreSpatialLocations([&](LatticeR<3>p){g.set(p,matAt(g.getPhysR(p)));});}geo.communicate();SuperIndicatorFfromIndicatorF3D<T>outside(new PeriodicXOutside,geo);UnitConverter<T,D>cv(dx,dt,240e-9,1.,nu,rhoP);SuperLattice<T,D>lat(cv,cub,load);dynamics::set<BGKdynamics>(lat,geo,1);if(pressure){boundary::set<T,D,boundary::LocalPressure<T,D,BGKdynamics<T,D>>>(lat,geo.getMaterialIndicator(4),geo.getMaterialIndicator(1),outside);boundary::set<T,D,boundary::LocalPressure<T,D,BGKdynamics<T,D>>>(lat,geo.getMaterialIndicator(5),geo.getMaterialIndicator(1),outside);}else{boundary::set<boundary::BounceBack>(lat,geo,4);boundary::set<boundary::BounceBack>(lat,geo,5);}dynamics::set<NoDynamics>(lat,geo,2);dynamics::set<NoDynamics>(lat,geo,3);AnalyticalConst3D<T,T>one(1),zero(0,0,0);lat.defineRhoU(geo.getMaterialIndicator({1,4,5}),one,zero);for(int m:{1,4,5})lat.iniEquilibrium(geo,m,one,zero);lat.addPostProcessor<stage::PostStream>(meta::id<BouzidiVelocityPostProcessor>{});lat.initialize();
 std::deque<Frame>ring;Event machEv,rhoEv,nanEv,firstEv;bool historyWritten=false;std::ofstream global(out/"global_extrema.csv");global<<"step,time_s,h_nm,wall_speed_m_s,max_Mach,max_speed_m_s,rho_min,rho_max,max_cell_ix,max_cell_iy,max_cell_iz,max_cell_material,max_cell_is_LocalPressure,max_cell_is_Bouzidi,max_cell_is_dual,active_links,dual_cells,invalid_links\n"<<std::setprecision(16);std::ofstream dual(out/"dual_boundary_history.csv");header(dual);
 for(int n=0;n<=diagSteps;++n){T h=hAt(n,move),uw=wallSpeed(n,move);auto lc=updateLinks(lat,geo,h,uw);if(n)lat.collideAndStream();Frame fr;fr.step=n;T maxMach=-1,rmin=1e300,rmax=-1e300;CellSnap mx;int index=0;for(int c=0;c<lat.getLoadBalancer().size();++c){auto&b=lat.getBlock(c);auto&g=geo.getBlockGeometry(c);b.forCoreSpatialLocations([&](LatticeR<3>p){int m=g.getMaterial(p);if(m!=1&&m!=4&&m!=5)return;auto s=snap(b,g,p,n);fr.cells.push_back(s);if(s.mach>maxMach||!s.finite){maxMach=s.mach;mx=s;}rmin=std::min(rmin,s.rho);rmax=std::max(rmax,s.rho);std::string dyn=typeid(*b.getDynamics(p[0],p[1],p[2])).name();if(!machEv.set&&s.mach>.05){machEv={true,n,index,"Mach>0.05",dyn,s};}if(!rhoEv.set&&(s.rho<.8||s.rho>1.2)){rhoEv={true,n,index,"rho outside [0.8,1.2]",dyn,s};}if(!nanEv.set&&!s.finite){nanEv={true,n,index,"NaN/Inf",dyn,s};}if(!firstEv.set&&(s.mach>.05||s.rho<.8||s.rho>1.2||!s.finite)){firstEv={true,n,index,!s.finite?"NaN/Inf":s.mach>.05?"Mach>0.05":"rho outside [0.8,1.2]",dyn,s};}if(s.dual)row(dual,s);index++;});}ring.push_back(std::move(fr));while((int)ring.size()>historySteps+1)ring.pop_front();if(firstEv.set&&!historyWritten){std::ofstream hf(out/"first_anomaly_cell_history.csv");header(hf);for(auto&old:ring)if(firstEv.index>=0&&firstEv.index<(int)old.cells.size())row(hf,old.cells[firstEv.index]);historyWritten=true;}global<<n<<","<<n*dt<<","<<h*1e9<<","<<uw<<","<<maxMach<<","<<cv.getPhysVelocity(mx.speed)<<","<<rmin<<","<<rmax<<","<<mx.ix<<","<<mx.iy<<","<<mx.iz<<","<<mx.mat<<","<<mx.lp<<","<<mx.bouz<<","<<mx.dual<<","<<lc[0]<<","<<lc[2]<<","<<lc[1]<<"\n";if(nanEv.set)break;}
 std::ofstream ev(out/"event_summary.txt");ev<<std::setprecision(16)<<std::boolalpha<<"case="<<which<<"\nmoving_bouzidi="<<move<<"\nLocalPressure="<<pressure<<"\nmaterial_conversion_enabled=false\nfirst_anomaly_present="<<firstEv.set<<"\nfirst_anomaly_kind="<<firstEv.kind<<"\nfirst_anomaly_step="<<firstEv.step<<"\nfirst_anomaly_cell="<<firstEv.cell.ix<<","<<firstEv.cell.iy<<","<<firstEv.cell.iz<<"\nfirst_anomaly_phys_nm="<<firstEv.cell.x*1e9<<","<<firstEv.cell.y*1e9<<","<<firstEv.cell.z*1e9<<"\nfirst_anomaly_material="<<firstEv.cell.mat<<"\nfirst_anomaly_LocalPressure="<<firstEv.cell.lp<<"\nfirst_anomaly_Bouzidi="<<firstEv.cell.bouz<<"\nfirst_anomaly_dual="<<firstEv.cell.dual<<"\nfirst_anomaly_dynamics_rtti="<<firstEv.dynamics<<"\nMach_limit_step="<<machEv.step<<"\nrho_limit_step="<<rhoEv.step<<"\nnonfinite_step="<<nanEv.step<<"\nlast_h_nm="<<hAt(nanEv.set?nanEv.step:diagSteps,move)*1e9<<"\nconversion_nodes=0\n";
 std::ofstream ec(out/"threshold_event_cells.csv");header(ec);if(machEv.set)row(ec,machEv.cell);if(rhoEv.set)row(ec,rhoEv.cell);if(nanEv.set)row(ec,nanEv.cell);
 log<<"completed=true\nexit_code=0\nfirst_anomaly_step="<<firstEv.step<<"\nnonfinite_step="<<nanEv.step<<"\n";std::ofstream rec(out/"run_record.txt");rec<<"run_id="<<run<<"\ncommand=./explicit_piston_boundary_intersection_diag "<<which<<"\nexit_code=0\nexit_reason=diagnostic_completed\n";return 0;}

int main(int argc,char**argv){initialize(&argc,&argv);if(singleton::mpi().getSize()!=1||argc!=2)return 2;char c=argv[1][0];if(c!='A'&&c!='B'&&c!='C')return 2;return run(c);}
