#include <olb.h>
#include <algorithm>
#include <array>
#include <cmath>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <limits>
#include <string>
#include <vector>
using namespace olb;
using T=double;
using D=descriptors::D3Q19<descriptors::BOUZIDI_DISTANCE,descriptors::BOUZIDI_VELOCITY>;
constexpr T dx=5e-9,dt=1e-11,Lx=240e-9,Ly=240e-9,dg=100e-9,rhoP=1000.,nu=1e-6;
constexpr int overlap=3,moveSteps=10000,holdSteps=5000,baseSteps=100;

class PeriodicXOutside final:public IndicatorF3D<T>{public:PeriodicXOutside(){this->_myMin={-1e9,-1e9,-1e9};this->_myMax={1e9,1e9,1e9};this->getName()="PeriodicXOutside";}bool operator()(bool o[1],const T r[3])override{T e=dx*1e-6;o[0]=r[1]<dx/2-e||r[1]>Ly-dx/2+e||r[2]<-dx/2-e||r[2]>192.5e-9+e;return true;}};
T smooth5(T s){s=std::clamp(s,T(0),T(1));return 10*s*s*s-15*s*s*s*s+6*s*s*s*s*s;}
T dsmooth5(T s){s=std::clamp(s,T(0),T(1));return 30*s*s*(1-s)*(1-s);}
T hAt(int n,bool moving){return moving?75e-9-10e-9*smooth5(T(std::min(n,moveSteps))/moveSteps):75e-9;}
T wallSpeed(int n,bool moving){return moving&&n<=moveSteps?-10e-9/(moveSteps*dt)*dsmooth5((T(n)-.5)/moveSteps):0;}
bool punch(T x,T z,T h){return z>=((x<60e-9||x>=180e-9)?h:h+dg);}
int matAt(const Vector<T,3>&r,T h){if(r[2]<0)return 2;if(punch(r[0],r[2],h))return 3;if(r[1]<dx)return 4;if(r[1]>Ly-dx)return 5;return 1;}

struct Stats{long long nf=0;T mass=0,vol=0,rmin=1e9,rmax=-1e9,maxu=0,lowOut=0,highOut=0;bool finite=true;};
template<class L,class G>Stats stats(L&l,G&g,const UnitConverter<T,D>&cv){Stats s;for(int c=0;c<l.getLoadBalancer().size();++c){auto&b=l.getBlock(c);auto&bg=g.getBlockGeometry(c);b.forCoreSpatialLocations([&](LatticeR<3>p){int m=bg.getMaterial(p);if(m!=1&&m!=4&&m!=5)return;auto cell=b.get(p);T u[3]{};cell.computeU(u);T r=cell.computeRho(),v=std::sqrt(u[0]*u[0]+u[1]*u[1]+u[2]*u[2]);s.nf++;s.mass+=r*rhoP*dx*dx*dx;s.vol+=dx*dx*dx;s.rmin=std::min(s.rmin,r);s.rmax=std::max(s.rmax,r);s.maxu=std::max(s.maxu,v);s.finite&=std::isfinite(r)&&std::isfinite(v);T uy=cv.getPhysVelocity(u[1]);if(m==4)s.lowOut-=r*rhoP*uy*dx*dx;if(m==5)s.highOut+=r*rhoP*uy*dx*dx;});}return s;}
template<class G>std::array<long long,6> counts(G&g){std::array<long long,6>n{};for(int c=0;c<g.getLoadBalancer().size();++c){auto&b=g.getBlockGeometry(c);b.forCoreSpatialLocations([&](LatticeR<3>p){int m=b.getMaterial(p);if(m>=0&&m<6)n[m]++;});}return n;}

template<class G>std::array<long long,5> auditPressure(G&geo,SuperIndicatorF3D<T>&outside){std::array<long long,5>a{};for(int c=0;c<geo.getLoadBalancer().size();++c){auto&bg=geo.getBlockGeometry(c);auto fs=geo.getMaterialIndicator(1);auto&f=fs->getBlockIndicatorF(c);auto&o=outside.getBlockIndicatorF(c);bg.forCoreSpatialLocations([&](LatticeR<3>p){int m=bg.getMaterial(p);if(m!=4&&m!=5)return;a[0]++;auto [ty,n]=computeBoundaryTypeAndNormal(f,o,p);Vector<int,3>e{0,m==4?-1:1,0};if(ty==DiscreteNormalType::Flat&&n==e)a[1]++;else if(n==Vector<int,3>{0,0,0})a[2]++;else a[3]++;});}a[4]=2400-a[0];return a;}

struct Tx{int covered=0;T source=0,added=0,error=0;};
template<class L,class G>Tx coverNodes(L&lat,G&geo,T oldh,T newh){Tx tx;for(int c=0;c<lat.getLoadBalancer().size();++c){auto&b=lat.getBlock(c);auto&g=geo.getBlockGeometry(c);std::vector<LatticeR<3>>todo;g.forCoreSpatialLocations([&](LatticeR<3>p){auto r=g.getPhysR(p);int old=g.getMaterial(p),neu=matAt(r,newh);if((old==1||old==4||old==5)&&neu==3)todo.push_back(p);});for(auto p:todo){auto src=b.get(p);T rho=src.computeRho();tx.source+=rho;std::vector<LatticeR<3>>recv;for(auto d:std::array<Vector<int,3>,5>{Vector<int,3>{0,0,-1},{1,0,-1},{-1,0,-1},{0,1,-1},{0,-1,-1}}){auto q=p+d;auto rr=g.getPhysR(q);int nm=matAt(rr,newh);if(nm==1||nm==4||nm==5)recv.push_back(q);}if(recv.empty())throw std::runtime_error("covered node has no persistent fluid receiver");T before=0;for(auto q:recv)before+=b.get(q).computeRho();for(auto q:recv){auto dst=b.get(q);for(int i=0;i<D::q;++i)dst[i]+=(src[i]+descriptors::t<T,D>(i))/recv.size();}T after=0;for(auto q:recv)after+=b.get(q).computeRho();tx.added+=after-before;tx.error+=(after-before)-rho;g.set(p,3);b.template defineDynamics<NoDynamics>(p);tx.covered++;}}geo.communicate();lat.communicate();(void)oldh;return tx;}

template<class L,class G>std::array<int,4> updateLinks(L&lat,G&geo,T h,T uw){int active=0,invalid=0,stale=0,conflict=0;for(int c=0;c<lat.getLoadBalancer().size();++c){auto&b=lat.getBlock(c);auto&g=geo.getBlockGeometry(c);b.forCoreSpatialLocations([&](LatticeR<3>p){auto cell=b.get(p);for(int q=0;q<D::q;++q){cell.template setFieldComponent<descriptors::BOUZIDI_DISTANCE>(q,-1);cell.template setFieldComponent<descriptors::BOUZIDI_VELOCITY>(q,0);}int m=g.getMaterial(p);if(m!=1&&m!=4&&m!=5)return;auto r=g.getPhysR(p);for(int q=1;q<D::q;++q){auto cvec=descriptors::c<D>(q);auto nb=p+cvec;int sm=g.getMaterial(nb);if(sm!=2&&sm!=3)continue;T qq=.5,vel=0;if(sm==3){T lo=0,hi=1;for(int k=0;k<50;++k){T a=(lo+hi)/2,x=r[0]+a*dx*cvec[0],z=r[2]+a*dx*cvec[2];if(punch(x,z,h))hi=a;else lo=a;}qq=(lo+hi)/2;vel=(cvec[2]*uw*dt/dx);}if(!(qq>=0&&qq<=1))invalid++;else{cell.template setFieldComponent<descriptors::BOUZIDI_DISTANCE>(q,qq);cell.template setFieldComponent<descriptors::BOUZIDI_VELOCITY>(q,vel);active++;}}});}lat.communicate();return{active,invalid,stale,conflict};}

int run(bool moving,const std::string&run){auto out=std::filesystem::path("output")/run;if(std::filesystem::exists(out)){std::cerr<<"exists\n";return 2;}std::filesystem::create_directories(out);singleton::directories().setOutputDir((out.string()+"/").c_str());std::ofstream log(out/"run.log");log<<std::setprecision(16)<<std::boolalpha;try{
 IndicatorCuboid3D<T>dom({Lx-dx,Ly-dx,195e-9},{dx/2,dx/2,-dx/2});CuboidDecomposition<T,3>cub(dom,dx,1);cub.setPeriodicity({true,false,false});HeuristicLoadBalancer<T>load(cub);SuperGeometry<T,3>geo(cub,load,overlap);for(int c=0;c<load.size();++c){auto&g=geo.getBlockGeometry(c);g.forCoreSpatialLocations([&](LatticeR<3>p){g.set(p,matAt(g.getPhysR(p),75e-9));});}geo.communicate();auto initialCounts=counts(geo);SuperIndicatorFfromIndicatorF3D<T>outside(new PeriodicXOutside,geo);auto pa=auditPressure(geo,outside);if(pa[0]!=2400||pa[1]!=2400||pa[2]||pa[3]||pa[4])throw std::runtime_error("pressure audit failed");
 UnitConverter<T,D>cv(dx,dt,240e-9,1.,nu,rhoP);SuperLattice<T,D>lat(cv,cub,load);dynamics::set<BGKdynamics>(lat,geo,1);boundary::set<T,D,boundary::LocalPressure<T,D,BGKdynamics<T,D>>>(lat,geo.getMaterialIndicator(4),geo.getMaterialIndicator(1),outside);boundary::set<T,D,boundary::LocalPressure<T,D,BGKdynamics<T,D>>>(lat,geo.getMaterialIndicator(5),geo.getMaterialIndicator(1),outside);dynamics::set<NoDynamics>(lat,geo,2);dynamics::set<NoDynamics>(lat,geo,3);AnalyticalConst3D<T,T>one(1),zero(0,0,0);lat.defineRhoU(geo.getMaterialIndicator({1,4,5}),one,zero);for(int m:{1,4,5})lat.iniEquilibrium(geo,m,one,zero);lat.addPostProcessor<stage::PostStream>(meta::id<BouzidiVelocityPostProcessor>{});lat.initialize();auto links0=updateLinks(lat,geo,75e-9,0);SuperVTMwriter3D<T>wr("explicit_piston_"+(moving?std::string("moving"):"baseline"),overlap);SuperGeometryF3D<T>gm(geo);gm.getName()="material";SuperLatticePhysVelocity3D<T,D>vel(lat,cv);vel.getName()="velocity_m_s";wr.addFunctor(gm);wr.addFunctor(vel);wr.createMasterFile();wr.write(0);
 Stats s0=stats(lat,geo,cv),prev=s0,fin=s0;T cumOut=0,maxResidual=0,maxMach=0,minRho=1e9,maxRho=-1e9,totalSrc=0,totalAdd=0,totalErr=0;int totalCov=0,maxInvalid=0,maxConflict=0;int total=moving?moveSteps+holdSteps:baseSteps;std::ofstream csv(out/"diagnostics.csv");csv<<"step,time_s,h_target_nm,h_actual_nm,wall_speed_m_s,wall_speed_lattice,converted_this_step,converted_cumulative,active_links,invalid_links,stale_links,boundary_conflicts,fluid_nodes,fluid_volume_m3,fluid_mass_kg,mass_relative_change,low_outward_flux_kg_s,high_outward_flux_kg_s,net_outward_flux_kg_s,cumulative_outward_mass_kg,mass_balance_residual_kg,relative_mass_balance_residual,conversion_source_lattice_mass,conversion_added_lattice_mass,conversion_error_lattice_mass,rho_min,rho_max,max_speed_m_s,Mach_max,finite\n"<<std::setprecision(16);
 for(int n=0;n<=total;++n){T hn=hAt(n,moving),hp=hAt(std::max(0,n-1),moving),uw=wallSpeed(n,moving);Tx tx;if(n&&hn<hp)tx=coverNodes(lat,geo,hp,hn);totalCov+=tx.covered;totalSrc+=tx.source;totalAdd+=tx.added;totalErr+=tx.error;auto li=updateLinks(lat,geo,hn,uw);maxInvalid=std::max(maxInvalid,li[1]);maxConflict=std::max(maxConflict,li[3]);if(n)lat.collideAndStream();fin=stats(lat,geo,cv);if(n)cumOut+=.5*((prev.lowOut+prev.highOut)+(fin.lowOut+fin.highOut))*dt;T res=fin.mass-s0.mass+cumOut;maxResidual=std::max(maxResidual,std::abs(res/s0.mass));T mach=fin.maxu/std::sqrt(T(1)/3);maxMach=std::max(maxMach,mach);minRho=std::min(minRho,fin.rmin);maxRho=std::max(maxRho,fin.rmax);csv<<n<<","<<n*dt<<","<<hn*1e9<<","<<hn*1e9<<","<<uw<<","<<uw*dt/dx<<","<<tx.covered<<","<<totalCov<<","<<li[0]<<","<<li[1]<<","<<li[2]<<","<<li[3]<<","<<fin.nf<<","<<fin.vol<<","<<fin.mass<<","<<(fin.mass-s0.mass)/s0.mass<<","<<fin.lowOut<<","<<fin.highOut<<","<<(fin.lowOut+fin.highOut)<<","<<cumOut<<","<<res<<","<<res/s0.mass<<","<<tx.source<<","<<tx.added<<","<<tx.error<<","<<fin.rmin<<","<<fin.rmax<<","<<cv.getPhysVelocity(fin.maxu)<<","<<mach<<","<<fin.finite<<"\n";prev=fin;if(n==moveSteps/2||n==moveSteps||n==total)wr.write(n);if(!fin.finite)throw std::runtime_error("non-finite state");}
 T finalRes=fin.mass-s0.mass+cumOut,dispMass=rhoP*Lx*Ly*10e-9;bool basePass=!moving&&totalCov==0&&std::abs((fin.mass-s0.mass)/s0.mass)<=1e-13&&maxResidual<=1e-13&&cv.getPhysVelocity(fin.maxu)<=1e-14&&counts(geo)==initialCounts;bool pos=moving&&std::abs(hAt(total,true)-65e-9)<=1e-21&&totalCov==4608;bool stable=fin.finite&&minRho>=.8&&maxRho<=1.2&&maxMach<=.05&&maxInvalid==0&&maxConflict==0;bool ledger=totalSrc>0&&std::abs(totalErr)/totalSrc<=1e-12;bool drain=cumOut>0&&std::abs(cumOut-dispMass)/dispMass<=.05;bool balance=maxResidual<=1e-3&&std::abs(finalRes/s0.mass)<=1e-3;bool pass=moving?(pos&&stable&&ledger&&drain&&balance):basePass;
 std::ofstream result(out/"result.txt");result<<std::setprecision(16)<<std::boolalpha<<"run_id="<<run<<"\nmode="<<(moving?"moving":"fixed")<<"\nPASS="<<pass<<"\nsteps_completed="<<total<<"\ndt_s="<<dt<<"\ntau="<<cv.getLatticeRelaxationTime()<<"\nmovement_steps="<<moveSteps<<"\nhold_steps="<<(moving?holdSteps:0)<<"\nT_s="<<moveSteps*dt<<"\nmax_wall_speed_m_s="<<1.875*10e-9/(moveSteps*dt)<<"\nmax_wall_speed_lattice="<<1.875*10e-9/(moveSteps*dx)<<"\ninitial_mass_kg="<<s0.mass<<"\nfinal_mass_kg="<<fin.mass<<"\ncumulative_outward_mass_kg="<<cumOut<<"\ncontinuous_displaced_mass_kg="<<dispMass<<"\nfinal_relative_mass_balance_residual="<<finalRes/s0.mass<<"\nmax_abs_relative_mass_balance_residual="<<maxResidual<<"\nconverted_nodes="<<totalCov<<"\nconversion_source_lattice_mass="<<totalSrc<<"\nconversion_added_lattice_mass="<<totalAdd<<"\nconversion_error_lattice_mass="<<totalErr<<"\nfinal_fluid_volume_m3="<<fin.vol<<"\ncontinuous_volume_reduction_m3="<<Lx*Ly*10e-9<<"\nmax_Mach="<<maxMach<<"\nrho_range="<<minRho<<","<<maxRho<<"\nmax_invalid_links="<<maxInvalid<<"\nmax_boundary_conflicts="<<maxConflict<<"\nposition_pass="<<pos<<"\nstability_pass="<<stable<<"\nledger_pass="<<ledger<<"\ndrain_pass="<<drain<<"\nbalance_pass="<<balance<<"\nbase_pass="<<basePass<<"\nexit_code="<<(pass?0:3)<<"\nexit_reason="<<(pass?"completed_all_frozen_checks_passed":"completed_one_or_more_frozen_checks_failed")<<"\n";log<<"completed="<<true<<"\nPASS="<<pass<<"\nexit_code="<<(pass?0:3)<<"\n";std::ofstream rec(out/"run_record.txt");rec<<"run_id="<<run<<"\ncommand=./explicit_piston_10nm "<<(moving?"moving":"baseline")<<"\nexit_code="<<(pass?0:3)<<"\n";return pass?0:3;
 }catch(const std::exception&e){log<<"exception="<<e.what()<<"\nexit_code=4\n";std::cerr<<e.what()<<"\n";return 4;}}

int main(int argc,char**argv){initialize(&argc,&argv);if(singleton::mpi().getSize()!=1)return 2;std::string mode=argc>1?argv[1]:"baseline";if(mode=="baseline")return run(false,"explicit_piston_fixed_precheck_v2_20260907");if(mode=="moving")return run(true,"explicit_piston_75to65_v2_20260907");return 2;}
