#include <olb.h>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <cmath>
#include <array>
using namespace olb; using T=double;
using D=descriptors::D3Q19<descriptors::BOUZIDI_DISTANCE,descriptors::BOUZIDI_VELOCITY>;
constexpr T dx=5e-9,dt=1e-11,Lx=240e-9,Ly=240e-9,dg=100e-9,rhoP=1000;
constexpr int baseSteps=200,moveSteps=1000,holdSteps=200;
struct S{long long nf=0,ns=0;T mass=0,maxu=0,rmin=1e9,rmax=-1e9;bool finite=true;};
T smooth(T x){x=std::clamp(x,T(0),T(1));return 10*x*x*x-15*x*x*x*x+6*x*x*x*x*x;}
T dsmooth(T x){x=std::clamp(x,T(0),T(1));return 30*x*x*(1-x)*(1-x);}
T hAt(int n,bool move){return move?75e-9-10e-9*smooth(T(n)/moveSteps):75e-9;}
bool punch(T x,T z,T h){return z>=((x<60e-9||x>=180e-9)?h:h+dg);}
template<class G> int matAt(G&r,T h){T x=r[0],y=r[1],z=r[2];if(z<0)return 2;if(punch(x,z,h))return 3;if(y<dx)return 4;if(y>Ly-dx)return 5;return 1;}
template<class L,class G>S stats(L&l,G&g){S s;for(int c=0;c<l.getLoadBalancer().size();++c){auto&b=l.getBlock(c);auto&bg=g.getBlockGeometry(c);b.forCoreSpatialLocations([&](LatticeR<3> p){int m=bg.getMaterial(p);if(m==1||m==4||m==5){auto q=b.get(p);T u[3]={};q.computeU(u);T r=q.computeRho(),v=std::sqrt(u[0]*u[0]+u[1]*u[1]+u[2]*u[2]);s.mass+=r;s.maxu=std::max(s.maxu,v);s.rmin=std::min(s.rmin,r);s.rmax=std::max(s.rmax,r);s.finite&=std::isfinite(r)&&std::isfinite(v);++s.nf;}else ++s.ns;});}return s;}
template<class G>void classifyPressureEdges(G&geo,const std::filesystem::path&out){std::ofstream d(out/"boundary_node_diagnostic.csv");d<<"x_nm,y_nm,z_nm,original_material,type,normal_x,normal_y,normal_z,xm,xp,ym,yp,zm,zp,action\n";for(int c=0;c<geo.getLoadBalancer().size();++c){auto&bg=geo.getBlockGeometry(c);auto bi4=geo.getMaterialIndicator(4);auto bi5=geo.getMaterialIndicator(5);auto fi=geo.getMaterialIndicator(1);auto oi=geo.getMaterialIndicator(0);auto&f=fi->getBlockIndicatorF(c);auto&o=oi->getBlockIndicatorF(c);bg.forCoreSpatialLocations([&](LatticeR<3>p){int m=bg.getMaterial(p);if(m!=4&&m!=5)return;auto [ty,n]=computeBoundaryTypeAndNormal(f,o,p);auto r=bg.getPhysR(p);bool flat=ty==DiscreteNormalType::Flat;d<<r[0]*1e9<<","<<r[1]*1e9<<","<<r[2]*1e9<<","<<m<<","<<int(ty)<<","<<n[0]<<","<<n[1]<<","<<n[2]<<","<<bg.getMaterial(p+Vector<int,3>{-1,0,0})<<","<<bg.getMaterial(p+Vector<int,3>{1,0,0})<<","<<bg.getMaterial(p+Vector<int,3>{0,-1,0})<<","<<bg.getMaterial(p+Vector<int,3>{0,1,0})<<","<<bg.getMaterial(p+Vector<int,3>{0,0,-1})<<","<<bg.getMaterial(p+Vector<int,3>{0,0,1})<<","<<(flat?"pressure":"solid_intersection")<<"\n";if(!flat)bg.set(p,6);});}geo.communicate();}
template<class L,class G>void update(L&l,G&g,T oldh,T newh,T uw,T&ledger,int&covered,int&links){
 covered=links=0;ledger=0;
 for(int c=0;c<l.getLoadBalancer().size();++c){auto&b=l.getBlock(c);auto&bg=g.getBlockGeometry(c);
  b.forCoreSpatialLocations([&](LatticeR<3> p){auto r=bg.getPhysR(p);int old=bg.getMaterial(p),neu=matAt(r,newh);auto cell=b.get(p);
   for(int q=0;q<D::q;++q){cell.template setFieldComponent<descriptors::BOUZIDI_DISTANCE>(q,-1);cell.template setFieldComponent<descriptors::BOUZIDI_VELOCITY>(q,0);}
   if(old!=3&&neu==3){T mass=cell.computeRho();std::array<decltype(p),5> cand={p+Vector<int,3>{0,0,-1},p+Vector<int,3>{1,0,-1},p+Vector<int,3>{-1,0,-1},p+Vector<int,3>{0,1,-1},p+Vector<int,3>{0,-1,-1}};int n=0;for(auto a:cand)if(bg.getMaterial(a)!=3&&bg.getMaterial(a)!=2)++n;if(!n)throw std::runtime_error("no receiver for covered node");for(auto a:cand)if(bg.getMaterial(a)!=3&&bg.getMaterial(a)!=2){auto z=b.get(a);for(int q=0;q<D::q;++q)z[q]+=cell[q]/n;}ledger+=mass;++covered;}
   bg.set(p,neu);
  });
 }
 g.communicate();
 dynamics::set<BGKdynamics>(l,g,1);boundary::set<T,D,boundary::LocalPressure<T,D,BGKdynamics<T,D>>>(l,g.getMaterialIndicator(4),g.getMaterialIndicator(1),g.getMaterialIndicator(0));boundary::set<T,D,boundary::LocalPressure<T,D,BGKdynamics<T,D>>>(l,g.getMaterialIndicator(5),g.getMaterialIndicator(1),g.getMaterialIndicator(0));dynamics::set<NoDynamics>(l,g,2);dynamics::set<NoDynamics>(l,g,3);
 for(int c=0;c<l.getLoadBalancer().size();++c){auto&b=l.getBlock(c);auto&bg=g.getBlockGeometry(c);b.forCoreSpatialLocations([&](LatticeR<3> p){int m=bg.getMaterial(p);if(m!=1&&m!=4&&m!=5)return;auto r=bg.getPhysR(p);auto cell=b.get(p);for(int q=1;q<D::q;++q){auto nb=p+descriptors::c<D>(q);if(bg.getMaterial(nb)==3){T rn[3]={r[0]+dx*descriptors::c<D>(q,0),r[1]+dx*descriptors::c<D>(q,1),r[2]+dx*descriptors::c<D>(q,2)};T lo=0,hi=1;for(int k=0;k<30;++k){T a=(lo+hi)/2,x=r[0]+a*(rn[0]-r[0]),z=r[2]+a*(rn[2]-r[2]);if(punch(x,z,newh))hi=a;else lo=a;}cell.template setFieldComponent<descriptors::BOUZIDI_DISTANCE>(q,(lo+hi)/2);T ul=uw*dt/dx;cell.template setFieldComponent<descriptors::BOUZIDI_VELOCITY>(q,descriptors::c<D>(q,2)*ul);++links;}}});}
 l.communicate();(void)oldh;
}
int main(int argc,char**argv){initialize(&argc,&argv);std::string mode=argc>1?argv[1]:"baseline";bool moving=mode=="moving";std::string run=moving?"open_drain_move10nm_fix1_20260907":"open_drain_fixed_h75_fix2_20260907";auto out=std::filesystem::path("output")/run;if(std::filesystem::exists(out)){std::cerr<<"exists\n";return 2;}std::filesystem::create_directories(out);singleton::directories().setOutputDir((out.string()+"/").c_str());IndicatorCuboid3D<T> dom({Lx-dx,Ly-dx,195e-9},{dx/2,dx/2,-dx/2});CuboidDecomposition<T,3> cub(dom,dx,1);cub.setPeriodicity({true,false,false});HeuristicLoadBalancer<T> load(cub);SuperGeometry<T,3> geo(cub,load,3);for(int c=0;c<load.size();++c){auto&g=geo.getBlockGeometry(c);g.forCoreSpatialLocations([&](LatticeR<3> p){auto r=g.getPhysR(p);g.set(p,matAt(r,75e-9));});}geo.communicate();classifyPressureEdges(geo,out);UnitConverter<T,D> cv(dx,dt,240e-9,1.,1e-6,rhoP);SuperLattice<T,D> lat(cv,cub,load);dynamics::set<BGKdynamics>(lat,geo,1);boundary::set<T,D,boundary::LocalPressure<T,D,BGKdynamics<T,D>>>(lat,geo.getMaterialIndicator(4),geo.getMaterialIndicator(1),geo.getMaterialIndicator(0));boundary::set<T,D,boundary::LocalPressure<T,D,BGKdynamics<T,D>>>(lat,geo.getMaterialIndicator(5),geo.getMaterialIndicator(1),geo.getMaterialIndicator(0));dynamics::set<NoDynamics>(lat,geo,2);dynamics::set<NoDynamics>(lat,geo,3);dynamics::set<NoDynamics>(lat,geo,6);AnalyticalConst3D<T,T> one(1),zero(0,0,0);lat.defineRhoU(geo.getMaterialIndicator({1,4,5}),one,zero);lat.iniEquilibrium(geo,1,one,zero);lat.iniEquilibrium(geo,4,one,zero);lat.iniEquilibrium(geo,5,one,zero);lat.addPostProcessor<stage::PostStream>(meta::id<BouzidiVelocityPostProcessor>{});lat.initialize();std::ofstream f(out/"statistics.csv");f<<"step,time_s,h_target_nm,h_actual_nm,wall_speed_m_s,covered,active_links,domain_mass_lattice,relative_domain_mass_change,conversion_mass_ledger,max_speed_m_s,rho_min,rho_max,finite\n"<<std::setprecision(16);S s0=stats(lat,geo);int total=moving?moveSteps+holdSteps:baseSteps;T hold=0;for(int n=0;n<=total;++n){T h=n<=moveSteps?hAt(n,moving):(moving?65e-9:75e-9),hp=n?((n-1<=moveSteps)?hAt(n-1,moving):h):h;T uw=(moving&&n<=moveSteps)?-10e-9/T(moveSteps*dt)*dsmooth(T(n)/moveSteps):0;T led=0;int cov=0,links=0;update(lat,geo,hp,h,uw,led,cov,links);if(n)lat.collideAndStream();auto s=stats(lat,geo);f<<n<<","<<n*dt<<","<<h*1e9<<","<<h*1e9<<","<<uw<<","<<cov<<","<<links<<","<<s.mass<<","<<(s.mass-s0.mass)/s0.mass<<","<<led<<","<<cv.getPhysVelocity(s.maxu)<<","<<s.rmin<<","<<s.rmax<<","<<s.finite<<"\n";}std::ofstream r(out/"run_record.txt");r<<"run_id="<<run<<"\nmode="<<mode<<"\ndt_s="<<dt<<"\nmove_steps="<<moveSteps<<"\nhold_steps="<<holdSteps<<"\nmax_wall_speed_m_s=1.875\nmax_wall_speed_lattice=0.00375\nexit_code=0\n";return 0;}
