#!/usr/bin/env python3
from pathlib import Path
import argparse, csv, xml.etree.ElementTree as ET
import numpy as np
import matplotlib.pyplot as plt

p=argparse.ArgumentParser(); p.add_argument('--run-id',default='static_h65_dx5'); a=p.parse_args(); root=Path(__file__).parent; out=root/'output'/a.run_id
rows=list(csv.DictReader((out/'geometry_parameters.csv').open())); q={r['parameter']:r['value'] for r in rows}; h=float(q['h']); dx=float(q['dx'])
tree=ET.parse(out/'ex240_material.vti'); image=tree.find('.//ImageData'); piece=tree.find('.//Piece'); ext=list(map(int,piece.attrib['Extent'].split())); nx,ny,nz=ext[1],ext[3],ext[5]; origin=list(map(float,image.attrib['Origin'].split())); vals=np.fromstring(tree.find('.//DataArray').text,sep=' ',dtype=np.uint8).reshape(nz,ny,nx)
colors=np.array([[0.93,0.93,0.93,1],[0.20,0.60,0.85,1],[0.40,0.40,0.40,1],[0.18,0.18,0.18,1]])
fig,ax=plt.subplots(figsize=(9,5.5)); ax.imshow(colors[vals[:,ny//2,:]],origin='lower',extent=[0,240,origin[2],origin[2]+nz*dx],interpolation='nearest',aspect='auto'); ax.axhline(0,color='k'); ax.annotate('',(25,h),(25,0),arrowprops=dict(arrowstyle='<->')); ax.text(29,22,'h = 65 nm\n(test sample)',va='center'); ax.annotate('',(120,h+100),(120,h),arrowprops=dict(arrowstyle='<->')); ax.text(150,h+50,'groove depth\n100 nm',va='center'); ax.set(xlabel='x (nm)',ylabel='z (nm)',title='SIM-EC1XT240 local static material field: x-z section'); ax.text(120,h+72,'groove / usable space',ha='center',color='white'); ax.text(30,h+12,'punch',ha='center',color='white'); ax.text(210,h+12,'punch',ha='center',color='white'); ax.text(120,-10,'fixed substrate',ha='center',color='white'); ax.axvline(0,color='m',ls='--');ax.axvline(240,color='m',ls='--');ax.text(120,origin[2]+nz*dx-4,'x periodic: half mesas join across seam',ha='center',va='top',color='m'); fig.tight_layout(); fig.savefig(out/'xz_section.png',dpi=240); fig.savefig(out/'xz_section.pdf'); plt.close(fig)
fig,ax=plt.subplots(figsize=(8,5)); plan=np.zeros((ny,nx),dtype=np.uint8); plan[:,12:36]=1; ax.imshow(np.array([[.2,.2,.2,1],[.2,.6,.85,1]])[plan],origin='lower',extent=[0,240,0,240],interpolation='nearest',aspect='equal'); ax.set(xlabel='x (nm)',ylabel='y (nm)',title='SIM-EC1XT240 local x-y plan (conditional solid footprint)'); ax.text(30,120,'left half mesa\n60 nm',ha='center',va='center',color='white');ax.text(120,120,'groove\n120 nm',ha='center',va='center',color='white');ax.text(210,120,'right half mesa\n60 nm',ha='center',va='center',color='white'); ax.axvline(0,color='m',ls='--');ax.axvline(240,color='m',ls='--');ax.text(120,230,'x± periodic; seam makes full 120 nm mesa',ha='center',color='m');ax.text(120,10,'y± periodic, Ly=240 nm is a local test choice',ha='center',color='white'); fig.tight_layout();fig.savefig(out/'xy_plan.png',dpi=240);fig.savefig(out/'xy_plan.pdf');plt.close(fig)
print('validated VTI shape',vals.shape,'and wrote figures to',out)
